# Generated by Django 3.2 on 2022-09-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_num',
            field=models.IntegerField(unique=True),
        ),
    ]
