# Generated by Django 3.2 on 2022-09-26 10:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_train_train_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='destination_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='runs_on',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=56),
        ),
        migrations.AlterField(
            model_name='train',
            name='source_time',
            field=models.TimeField(),
        ),
    ]
