# Generated by Django 3.2 on 2022-09-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_auto_20220926_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
