# Generated by Django 3.2 on 2022-09-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_alter_train_train_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'verbose_name': 'Train', 'verbose_name_plural': 'Trains'},
        ),
    ]
