# Generated by Django 3.2 on 2022-09-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_auto_20220927_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='destination_time',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='source_time',
            new_name='departure_time',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='train_num',
            new_name='train_number',
        ),
        migrations.RemoveField(
            model_name='train',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='train',
            name='source',
        ),
        migrations.RemoveField(
            model_name='train',
            name='total_time_in_hours',
        ),
        migrations.AddField(
            model_name='train',
            name='destination_short_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='destination_station',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='source_short_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='source_station',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='station_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='station_name_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
