# Generated by Django 3.2 on 2022-09-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_auto_20220927_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainRoute',
        ),
    ]
