# Generated by Django 3.2 on 2022-09-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_delete_trainroute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='station_name_name',
            new_name='station_name',
        ),
    ]
