# Generated by Django 3.2 on 2022-09-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_rename_station_name_name_train_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='station_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='train',
            name='station_name',
            field=models.CharField(max_length=255),
        ),
    ]
