# Generated by Django 3.2 on 2022-09-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_auto_20220927_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
