# Generated by Django 3.2 on 2022-10-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_alter_train_train_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['train_number', 'sequence'], 'verbose_name': 'Train', 'verbose_name_plural': 'Trains'},
        ),
    ]
