# Generated by Django 3.2 on 2022-10-06 08:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0013_auto_20221006_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainWithStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sequence', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='train',
            name='station',
            field=models.ManyToManyField(related_name='station', through='train.TrainWithStations', to='train.Station'),
        ),
    ]
