# Generated by Django 3.2 on 2022-10-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0014_auto_20221006_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
    ]
