# Generated by Django 3.2 on 2022-10-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0015_alter_station_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='station',
            field=models.ManyToManyField(related_name='stations', through='train.TrainWithStations', to='train.Station'),
        ),
    ]
