# Generated by Django 3.2 on 2022-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0016_alter_train_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainwithstations',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
