# Generated by Django 3.2 on 2022-10-10 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0017_trainwithstations_base_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainwithstations',
            name='arrival',
            field=models.TimeField(default=datetime.datetime(2022, 10, 10, 5, 4, 7, 319216, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainwithstations',
            name='departure',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
