# Generated by Django 3.2 on 2022-10-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0020_berth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boogy',
            new_name='Boggy',
        ),
        migrations.AlterField(
            model_name='berth',
            name='lower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berth',
            name='middle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berth',
            name='side_lower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berth',
            name='side_upper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berth',
            name='upper',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
