# Generated by Django 3.2 on 2022-10-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0023_boggy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berth',
            name='name',
        ),
        migrations.AddField(
            model_name='berth',
            name='boggy',
            field=models.ForeignKey(default=432, on_delete=django.db.models.deletion.CASCADE, to='train.boggy'),
            preserve_default=False,
        ),
    ]
