# Generated by Django 3.2 on 2022-10-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0024_auto_20221013_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berth',
            name='boggy',
        ),
        migrations.AddField(
            model_name='berth',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
