# Generated by Django 3.2 on 2022-10-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0025_auto_20221013_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berth',
            options={'ordering': ['-date'], 'verbose_name': 'Berth', 'verbose_name_plural': 'Berths'},
        ),
        migrations.AlterModelOptions(
            name='boggy',
            options={'ordering': ['-date'], 'verbose_name': 'Boggy', 'verbose_name_plural': 'Boggies'},
        ),
    ]
