# Generated by Django 3.2 on 2022-10-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0026_auto_20221014_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berth',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
