# Generated by Django 4.1.2 on 2022-10-18 05:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0027_alter_berth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='runs_on',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=100),
        ),
    ]
