# Generated by Django 3.2 on 2022-09-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220927_0456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassengerDetails',
            new_name='PassengerDetail',
        ),
        migrations.AlterModelOptions(
            name='passengerdetail',
            options={'verbose_name': 'PassengerDetail', 'verbose_name_plural': 'PassengerDetails'},
        ),
        migrations.AlterModelOptions(
            name='reservationchartfortrain',
            options={'verbose_name': 'ReservationChartForTrain', 'verbose_name_plural': 'ReservationChartForTrains'},
        ),
        migrations.AlterModelOptions(
            name='userjourney',
            options={'verbose_name': 'UserJourney', 'verbose_name_plural': 'UserJourneys'},
        ),
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'verbose_name': 'WaitingList', 'verbose_name_plural': 'WaitingLists'},
        ),
    ]
