# Generated by Django 3.2 on 2022-10-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20220927_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjourney',
            name='passengers',
        ),
    ]
