# Generated by Django 3.2 on 2022-10-03 10:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_userjourney_passengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('passenger_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.passengerdetail')),
                ('user_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.userjourney')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userjourney',
            name='passengers',
            field=models.ManyToManyField(related_name='passengers', through='reservation.Reservation', to='reservation.PassengerDetail'),
        ),
    ]
