# Generated by Django 3.2 on 2022-10-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20221003_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='gender',
            field=models.CharField(choices=[('LOWER', 'Lower'), ('MIDDLE', 'Middle'), ('UPPER', 'Upper'), ('SIDEUPPER', 'Sideupper')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
