# Generated by Django 3.2 on 2022-10-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_passengerdetail_birth_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationchartfortrain',
            name='user_journey',
            field=models.ManyToManyField(blank=True, to='reservation.UserJourney'),
        ),
        migrations.AlterField(
            model_name='reservationchartfortrain',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, to='reservation.WaitingList'),
        ),
    ]
