# Generated by Django 3.2 on 2022-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20221003_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjourney',
            name='status1',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
