# Generated by Django 3.2 on 2022-10-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0012_alter_train_options'),
        ('reservation', '0012_remove_userjourney_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdetail',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userjourney',
            name='destination_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_station', to='train.city'),
        ),
        migrations.AlterField(
            model_name='userjourney',
            name='source_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_station', to='train.city'),
        ),
        migrations.AlterField(
            model_name='userjourney',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='train.train'),
        ),
    ]
