# Generated by Django 3.2 on 2022-10-06 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_reservationchartfortrain_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationchartfortrain',
            options={'ordering': ['date'], 'verbose_name': 'Reservation Chart For Train', 'verbose_name_plural': 'Reservation Chart For Trains'},
        ),
        migrations.AddField(
            model_name='userjourney',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userjourney',
            name='pnr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
