# Generated by Django 3.2 on 2022-10-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_auto_20221006_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='user_journey',
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='waiting_number',
        ),
    ]
