# Generated by Django 3.2 on 2022-10-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_auto_20221007_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdetail',
            name='birth_preference',
            field=models.CharField(blank=True, choices=[('LOWER', 'Lower Berth'), ('MIDDLE', 'Middle Berth'), ('UPPER', 'Upper Berth'), ('SIDELOWER', 'Side Lower Berth'), ('SIDEMIDDLE', 'Side Middle Berth'), ('SIDEUPPER', 'Side Upper Berth')], max_length=15, null=True),
        ),
    ]
