# Generated by Django 3.2 on 2022-10-13 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0023_boggy_date'),
        ('reservation', '0018_alter_passengerdetail_birth_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationchartfortrain',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_charts', to='train.train'),
        ),
    ]
