# Generated by Django 3.2 on 2022-10-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0021_rename_birth_preference_passengerdetail_berth_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationchartfortrain',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservationchartfortrain',
            name='vacant_seats',
            field=models.IntegerField(default=0),
        ),
    ]
