# Generated by Django 3.2 on 2022-10-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0022_auto_20221013_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationchartfortrain',
            name='total_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationchartfortrain',
            name='vacant_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
