# Generated by Django 3.2 on 2022-10-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0025_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
