# Generated by Django 3.2 on 2022-10-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0026_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passengerdetail',
            name='berth_preference',
            field=models.CharField(blank=True, choices=[('LOWER', 'Lower Berth'), ('MIDDLE', 'Middle Berth'), ('UPPER', 'Upper Berth'), ('SIDE_LOWER', 'Side Lower Berth'), ('SIDE_MIDDLE', 'Side Middle Berth'), ('SIDE_UPPER', 'Side Upper Berth')], max_length=15, null=True),
        ),
    ]
